### ISSUE TITLE
code to generate "purifiedpbmcdataset.h5ad

### ISSUE THREAD

**Issue by skr3178** [YosefLab/scVI-data#7]
Hi, 
Thank you for sharing this dataset.
I am new to genomics and programming and want to learn how this dataset was generated. 
Can I request to share the code for generating this dataset from source? This would be helpful.

Thanks

**Comment by adamgayoso** [comment]
The datasets can be found on 10x's website [here](https://www.10xgenomics.com/resources/datasets?query=&page=1&configure%5Bfacets%5D%5B0%5D=chemistryVersionAndThroughput&configure%5Bfacets%5D%5B1%5D=pipeline.version&configure%5BhitsPerPage%5D=500)

Each cell type can be loaded using scanpy's read_10x functions

<img width="959" alt="Screen Shot 2022-02-25 at 3 47 35 PM" src="https://user-images.githubusercontent.com/10859440/155817884-b20edc2f-67cd-474c-9e8c-afddb16fa0d1.png">
